added frame queue limit
Banuba/OEP-module pull request #22
Opened 2022-08-01 10:35 UTC by sdk-banuba

2022-08-01 10:37 UTC, sdk-banuba commented
Добавил ограничение очереди кадров. А так же сделал так что бы обрабатывался всегда один последний кадр.

2022-08-01 10:38 UTC, sdk-banuba commented on offscreen_effect_player/offscreen_effect_player.cpp
> +            callback(nullptr);
если кадров в очереди уже 5 или более, то даже не добавляем текущий кадр в очередь. Выполняем колбэк и выходим

2022-08-01 10:38 UTC, sdk-banuba commented on offscreen_effect_player/offscreen_effect_player.cpp
> +                if (m_incoming_frame_queue_task_count == 1) {
в остальном логика осталась неизменной

2022-08-01 11:42 UTC, dmitrystoyanovsky commented on offscreen_effect_player/offscreen_effect_player.cpp
> +            callback(nullptr);
Давай попробуем, но случай 1 одали 1 вернули может работать не правильно, т.к. 3,4 дропнули а потом вернули фрейм с номером 2. Тут лучше сразу из функции фозвращать fail.

2022-08-01 11:44 UTC, dmitrystoyanovsky commented on offscreen_effect_player/offscreen_effect_player.cpp
> +            callback(nullptr);
Лучше пересмотреть интерфейс и возвращать bool как индикатор приняли ферейм или дропнули.

2022-08-03 10:00 UTC, dmitrystoyanovsky approved these changes

2022-08-03 10:00 UTC, dmitrystoyanovsky commented on interfaces/offscreen_effect_player.hpp
> +         * @return false if the frame was dropped, otherwise true
return false if the frame is rejected because of too many items in the internal queue of frames, otherwise true

2022-08-03 10:57 UTC, dmitrystoyanovsky requested changes

2022-08-03 10:57 UTC, dmitrystoyanovsky commented on offscreen_effect_player/offscreen_effect_player.cpp
> +        if (m_incoming_frame_queue_task_count >= 5) {
make 5 constant

2022-08-03 10:57 UTC, dmitrystoyanovsky commented on offscreen_effect_player/offscreen_effect_player.hpp
> +        std::mutex m_actual_process_data_mtx;
Please remove and just leave the change to return bool from process_image_async

2022-08-03 13:04 UTC, merged